TEMPLATES_FOLDER_NAME = "templates"

DEFAULT_TEMPLATE_FOLDER_NAME = "template-data"
DEFAULT_SAMPLE_FOLDER_NAME = "sample-data"
SAMPLE_FOLDER_NAME_ENV = "TEMPLATE_FRAMEWORK_SAMPLE_FOLDER"
TEMPLATE_LOCAL_FILENAME_ENV = "TEMPLATE_FRAMEWORK_LOCAL_FILENAME"

TEMPLATE_TYPE_SCAFFOLD = "scaffold"
TEMPLATE_TYPE_PLUGIN = "plugin"
TEMPLATE_TYPE_RESOURCE = "resource"
TEMPLATES_TYPES = [
    TEMPLATE_TYPE_SCAFFOLD,
    TEMPLATE_TYPE_PLUGIN,
    TEMPLATE_TYPE_RESOURCE,
]
